version: '3.4'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mul_api_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    
  web:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: 51945924b5222dd3db4f3a5d81b0fee56fcc7585460a1dba6f0db17d1784c6976a23c48cc17cf8cf056b260e47395b911c59f417bf6f42dd114f633b26fd4bdb

volumes:
  postgres_data: