version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mul_api_development
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - bundle-cache:/usr/local/bundle
      # SSH agent forwarding
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - "3001:3001"
    networks:
      - app-network

volumes:
  postgres-data:
  bundle-cache:

networks:
  app-network:
    driver: bridge